[build-system]
requires = ["setuptools>=60.0","wheel"]

build-backend = "setuptools.build_meta"

[project]
name = "task-tracker"
version = "0.1.0"
dependencies = []

[project.scripts]
task-tracker = "task-tracker.main:main"